// Generated by CoffeeScript 1.4.0
(function() {

  window.onload = function() {
    return new Radial(document.getElementById('nav'), document.getElementById('upperRight'), 75);
  };

}).call(this);
